items_per_page: 18
unit_of_issue: "EA"
running_spares: "0"
qty_max_reasonable: 999

layout:
  x_a_center: 1.05
  x_b: 1.55
  x_c_center: 6.42
  x_d_center: 7.28
  x_e: 8.05
  x_f: 8.68
  top: 7.00
  bottom: 0.95
  y_block_shift: 0.12
