items_per_page: 18
unit_of_issue: "EA"
running_spares: "0"
qty_max_reasonable: 999

layout:
  x_a_center: 1.015
  x_b: 1.40
  x_c_center: 5.50
  x_d_center: 6.125
  x_e: 6.60
  x_f: 7.22
  top: 8.70
  bottom: 2.05
  y_block_shift: 0.18
